version: '3.8'

x-mongo-secrets: &mongo-credentials
  MONGO_USER: &mongo-user root
  MONGO_PASS: &mongo-pass toor


x-common-settings: &common-settings
  restart: always

services:
  mongo:
    <<: *common-settings
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: *mongo-user
      MONGO_INITDB_ROOT_PASSWORD: *mongo-pass
    ports:
      - 27017:27017
    volumes:
      - mongo-db-data:/data/db

  payments:
    build:
      context: .
      dockerfile: payments/Dockerfile
    depends_on:
      - mongo
    ports:
      - "2222:2222"
    restart: always

  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    container_name: kafka-2.12
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
      image: zookeeper:3.4
      container_name: zookeeper-3.4
      hostname: zookeeper
      ports:
        - "2181:2181"

volumes:
  mongo-db-data:
